#
# A sample configmap for mplat-system
# This configmap does not define dsf.mbanking.url, in order to
# make it easier to configure by local deployment configs
# This template enables SSL
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    group: main
    scope: mplat-system
  name: mplat-system
data:
  logback-spring.xml: |-
    <configuration>
    <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
      <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
        <level>${LOGGING_LEVEL_ROOT}</level>
      </filter>
      <encoder class="net.logstash.logback.encoder.LogstashEncoder"></encoder>
      </appender>
      <root level="DEBUG">
        <appender-ref ref="CONSOLE" />
      </root>
    </configuration>
  application.yml: |-
    server:
      servlet:
        contextPath: /
      ssl:
        enabled: true
        key-store: ${KEYSTORE_JKS}
        key-store-provider: SUN
        key-store-type: JKS
    # actuator
    management:
      # Needed for Fabric8 to behave properly
      context-path:
      server.servlet.context-path: /
      security.enabled: false
      endpoint:
        health:
          show-details: always
      endpoints:
        web:
          base-path: /
          exposure:
            include: health, info, ping, env, clientdetails, version, dependencies, prometheus, metrics
    security:
      basic.enabled: false
